AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Environment:
      Variables:
        APP_ENV: prod
Resources:
  Website:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: kontatudo-site
      CodeUri: s3://kontatudo-lambda/0c1ffaa8b5a01d1a81eab9d7116121b7
      Handler: public/index.php
      Timeout: 30
      MemorySize: 1024
      Runtime: provided
      Layers:
      - arn:aws:lambda:us-east-2:209497400698:layer:php-73-fpm:7
      Events:
        HttpRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        HttpSubPaths:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
  Console:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: kontatudo-console
      CodeUri: s3://kontatudo-lambda/0c1ffaa8b5a01d1a81eab9d7116121b7
      Handler: bin/console
      Timeout: 120
      Runtime: provided
      Layers:
      - arn:aws:lambda:us-east-2:209497400698:layer:php-73-fpm:7
      - arn:aws:lambda:us-east-2:209497400698:layer:console:7
Outputs:
  DemoApi:
    Description: URL of our function in the *Prod* environment
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
